# Generated by Django 3.1.1 on 2020-09-22 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='courseUrl',
            field=models.URLField(default='www.google.com'),
        ),
    ]
